language: python
python:
  - "3.7"
install:

  - "pip install pycodestyle"
  - "pip install -e ."

# command to run tests
script:
  # tests

  - python setup.py test
  - pycodestyle tabcmd tests
  - pytest