# Site settings
title: tabcmd
email: scot.marvin@tableau.com
description: Connect to your web data from Tableau.
baseurl: "/tabcmd"
# permalink: pretty
defaults:
  -
    scope:
      path: "" # Apply to all files
    values:
      layout: "default"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    toc_levels: 2..2

# Exclude
exclude: ['node_modules', 'vendor']

theme: jekyll-theme-minimal
