class CommandsMap:
    commands_hash_map = {"login": "LoginCommand",
                         "createproject": "CreateProjectCommand",
                         "deleteproject": "DeleteProjectCommand",
                         "creategroup": "CreateGroupCommand",
                         "deletegroup": "DeleteGroupCommand",
                         "createusers": "CreateUserCommand",
                         "deleteusers": "DeleteUserCommand",
                         "removeusers": "RemoveUserCommand",
                         "logout": "LogoutCommand",
                         "addusers": "AddUserCommand",
                         "createsiteusers": "CreateSiteUsersCommand",
                         "createsite": "CreateSiteCommand",
                         "deletesite": "DeleteSiteCommand",
                         "deletesiteusers": "DeleteSiteUsersCommand",
                         "editsite": "EditSiteCommand",
                         "listsites": "ListSiteCommand"}
